/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.example.matrixmultiply;

public class exampleJNI {
  public final static native int gcd(int jarg1, int jarg2);
  public final static native void Foo_set(double jarg1);
  public final static native double Foo_get();
  public final static native void ra_set(int jarg1);
  public final static native int ra_get();
  public final static native void ca_set(int jarg1);
  public final static native int ca_get();
  public final static native void rb_set(int jarg1);
  public final static native int rb_get();
  public final static native void cb_set(int jarg1);
  public final static native int cb_get();
  public final static native long initMatrix(int jarg1, int jarg2, int jarg3, int jarg4);
  public final static native int getItemFromMatrix(long jarg1, int jarg2, int jarg3);
  public final static native void parallelMatrixMultiply(long jarg1, int jarg2, int jarg3, int jarg4);
  public final static native void matrixMultiply(long jarg1);
}
